version: '2'
services:
  adjective:
    build: ./adjective-service
    image: recursivechaos/adjective
    ports:
      - "8010:8080"
  noun:
    build: ./noun-service
    image: recursivechaos/noun
    ports:
      - "8020:8080"