version: '2'
services:
  gateway:
    build: ./api-gateway
    image: recursivechaos/gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  adjective:
    build: ./adjective-service
    image: recursivechaos/adjective
    ports:
      - "8010:8010"
  noun:
    build: ./noun-service
    image: recursivechaos/noun
    ports:
      - "8020:8020"